import Header from "./components/header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Roxiler System Coding Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className = "mx-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
